---
# Handlers for Cloudera Manager Server.

- include_vars: ../../../group_vars/scm_server.yml

- name: restart cloudera-scm-server
  service:
    name: cloudera-scm-server
    state: restarted
    notify:
      - wait cloudera-scm-server

- name: wait cloudera-scm-server
  wait_for:
    host: "{{ hostvars[scm_hostname]['inventory_hostname'] }}"
    port: 7180
    #port: {{ scm_port }}
    delay: 30
    state: started
    timeout: 300
